substitutions:
  _COMPUTE_ZONE: us-west1
  _CLUSTER_NAME: hotel-search-cluster-1

steps:
  # Running tests before building image as it can be faster to test.
  # Also, the unit tests should not be part of the delpoyments, as the image size increases 
  # and also they do not serve any purpose in deployed image.
  - name: 'gcr.io/cloud-builders/npm'
    id: Install test dependencies
    args: ['install']
    dir: 'HotelSearchCloud/test/'
  
  - name: 'gcr.io/cloud-builders/npm'
    id: Install NLP service dependencies
    args: ['install']
    dir: 'HotelSearchCloud/nlp_service/'
  
  - name: 'gcr.io/cloud-builders/npm'
    id: Install Search service dependencies
    args: ['install']
    dir: 'HotelSearchCloud/search_service/'
  
  - name: 'gcr.io/cloud-builders/npm'
    id: Run tests
    args: ['test']
    dir: 'HotelSearchCloud/test/'
  # Building and pushing the NLP service image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build and push NLP service
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA', './nlp_service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA']

  # Building and pushing the Search service image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build and push Search service
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA', './search_service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA']

  # Updating the Kubernetes deployment to use the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/nlp-service'
    - 'nlp-service=gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA'
    - '--namespace'
    - 'mongodb'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/search-service'
    - 'search-service=gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA'
    - '--namespace'
    - 'mongodb'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

images:
  - 'gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA'