substitutions:
  _COMPUTE_ZONE: us-west1
  _CONTAINER_CLUSTER: hotel-search-cluster-1

steps:
  # Building and pushing the NLP service image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build and push NLP service
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA', './nlp_service']
    dir: 'HotelSearchCloud/'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA']

  # Building and pushing the Search service image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build and push Search service
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA', './search_service']
    dir: 'HotelSearchCloud/'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA']

  # Updating the Kubernetes deployment to use the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/nlp-service'
    - 'nlp-service=gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA'
    - '--namespace'
    - 'mongodb'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/search-service'
    - 'search-service=gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA'
    - '--namespace'
    - 'mongodb'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

images:
  - 'gcr.io/$PROJECT_ID/nlp_service_app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/search_service_app:$COMMIT_SHA'