apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32000
    protocol: TCP
  selector:
    app: mongodb-svc
  type: NodePort
